### PR TITLE
chore: Remove deprecated AddCertificateAuthentication extensions

### LINKED ISSUE #355: Remove deprecated `AddCertificateAuthentication` extensions
**Is your feature request related to a problem? Please describe.**
Due to the fact that we moved the certificate authentication authentication from `mvcOptions` to `mvcOptions.Filters`, the `.AddCertificateAuthentication` extensions were marked as deprecated and replaced with `.AddCertificateAuthenticationFilter` extensions.

**Describe the solution you'd like**
Remove the deprecated `.AddCertificateAuthentication` extensions in the `Arcus.WebApi.Security` project.

**Additional context**
Was made deprecated in #351

### PR DESCRIPTION
**Pull request by Roeland54**
Closes #355

### CODE REVIEW

**Comment by Roeland54** [comment]
Seams like the api of nuget.org was not accessible from the pipeline when the integration test where running?

**Comment by stijnmoreels** [comment]
> Seams like the api of nuget.org was not accessible from the pipeline when the integration tests where running?

Had it on other Arcus libraries, too. Was bc the MyGet storage was at it limits 😅 . Should be fixed.

**Review by stijnmoreels — APPROVED** [review]
Great job in removing this, and thx so much for not ruining the code formatting and only removing whitespace. Is greatly appreciated! 🎉
And thanks again for all your PR's on this library! Super enthusiasm.

**Review by fgheysels — APPROVED** [review]

**Pull request merged**
