### PR TITLE
Feature - move correlation functionality to 'Logging' project

### LINKED ISSUE #134: Should we merge Arcus.WebApi.Logging & Arcus.WebApi.Correlation?
**Is your feature request related to a problem? Please describe.**
Should we merge Arcus.WebApi.Logging & Arcus.WebApi.Correlation into one 📦 as they are related?

/cc @fgheysels @gverstraete

### PR DESCRIPTION
**Pull request by stijnmoreels**
Closes #134

### CODE REVIEW

**Comment by stijnmoreels** [comment]
I didn't move the obsolete types from the correlation project though, since it's new in logging anyway.

**Comment by tomkerkhove** [comment]
We're planning a v1.0 release so you can just break everything, no need to deprecate things.

Can you update the docs as well please?

**Comment by stijnmoreels** [comment]
> We're planning a v1.0 release so you can just break everything, no need to deprecate things.
> 
> Can you update the docs as well please?

Ok, let's destroy everything. 😲

**Comment by stijnmoreels** [comment]
> We're planning a v1.0 release so you can just break everything, no need to deprecate things.
> 
> Can you update the docs as well please?

Lets wait for Observability v0.1.0 so we can use that instead of previews maybe.

**Comment by stijnmoreels** [comment]
Hmm, build failure something about .NET SDK? 🤔

**Comment by tomkerkhove** [comment]
Maybe due to https://status.dev.azure.com/_event/182998791

**Comment by tomkerkhove** [comment]
> > We're planning a v1.0 release so you can just break everything, no need to deprecate things.
> > Can you update the docs as well please?
> 
> Lets wait for Observability v0.1.0 so we can use that instead of previews maybe.

Wait with doing what exactly? We're not going to ship v1.0 yet if that's what you are asking :)

**Comment by stijnmoreels** [comment]
> > > We're planning a v1.0 release so you can just break everything, no need to deprecate things.
> > > Can you update the docs as well please?
> > 
> > 
> > Lets wait for Observability v0.1.0 so we can use that instead of previews maybe.
> 
> Wait with doing what exactly? We're not going to ship v1.0 yet if that's what you are asking :)

Yes, that, watiting with the release so we can update with the first full Observability NuGet release (v0.1.0)..

**Comment by stijnmoreels** [comment]
Can I merge despite this build failure stuff? All the tests are green though 😖.

**Comment by tomkerkhove** [comment]
> Can I merge despite this build failure stuff? All the tests are green though 😖.

Looks like we have failing tests though

**Comment by stijnmoreels** [comment]
> > Can I merge despite this build failure stuff? All the tests are green though 😖.
> 
> Looks like we have failing tests though

You sure? I don't see it here:
image

**Comment by tomkerkhove** [comment]
That log page might be bugged then because there are clear failures on :
https://dev.azure.com/codit/Arcus/_build/results?buildId=43613&view=ms.vss-test-web.build-test-results-tab
image
image

Had a look again and it was reported above the 2nd test run
https://dev.azure.com/codit/Arcus/_build/results?buildId=43613&view=logs&j=6b58850f-3858-5a05-33e2-5e41cbf03c4e&t=67dc9284-07ce-51a8-a760-4b4b8180fb92&l=1165 for Test run for `/home/vsts/work/1/s/src/Arcus.WebApi.Tests.Unit/bin/release/netcoreapp3.0/Arcus.WebApi.Tests.Unit.dll(.NETCoreApp,Version=v3.0)`

There is a summary at the bottom for both test runs:
> Publishing test results to test run '1029734'
> Test results remaining: 100. Test run id: 1029734
> Publishing test results to test run '1029736'
> Test results remaining: 99. Test run id: 1029736

**Pull request closed without merging**
