### PR TITLE
fix: use Arcus NuGet version ranges

### PR DESCRIPTION
**Pull request by stijnmoreels**
Let's use NuGet version ranges to include Arcus dependencies so we can more easily support multiple Arcus packages in a single project.

Relates to https://github.com/arcus-azure/arcus/issues/129

### CODE REVIEW

**Comment by stijnmoreels** [comment]
Something like this, @tomkerkhove ?

**Comment by tomkerkhove** [comment]
No because now you're using 3.0 as inclusive but it should be exclusive

**Comment by stijnmoreels** [comment]
> No because now you're using 3.0 as inclusive but it should be exclusive

Just saw it, pushed already. 😄

**Comment by stijnmoreels** [comment]
> No because now you're using 3.0 as inclusive but it should be exclusive

Just saw it, pushed already. 😄

**Review by tomkerkhove — APPROVED** [review]

**Comment by tomkerkhove** [comment]
Based on https://github.com/arcus-azure/arcus.webapi/issues/230 I would actually increase it to at minimum `2.0.1`

**Pull request merged**
